### ISSUE TITLE
Feature: CI/CD cross-compile Dockerfiles automatically

### ISSUE THREAD

**Issue by tbrodbeck** [JanLahmann/Qoffee-Maker#27]
Ideas:
- use Github actions

**Comment by max-simon** [comment]
Problem: https://github.com/JanLahmann/Qoffee-Maker/runs/5662744552?check_suite_focus=true#step:10:246

**Comment by tbrodbeck** [comment]
Problem ist jetzt gelöst: https://github.com/JanLahmann/Qoffee-Maker/actions/runs/2301929511
Also Cross Compile funktioniert.

Jetzt brauchen wir nur noch eine funktionierende Pipeline. 

@max-simon Ich habe gesehen, dass du ein dev und ein prod Deployment auf OCP gestellt hast. Vielleicht wäre es eine Idee, dann statt GH Actions Tekton Pipelines zu benutzen und den Cross-Compile + CICD + ArgoCD etc auf OCP zu machen? Dann hätten wir halt wirklich Contiuous Deployment.

Alternativ kann man vielleicht die Compilation auf GH Actions machen und dann am Ende der Actions Pipeline eine Webhook callen, die dann eine Tekton Pipeline startet 🤔  Das wäre eigentlich die optimale Lösung denke ich.
